baseURL = "https://sushantarya.github.io/"
languageCode = "en-us"
title = "Linux Networking Deep Dives"
theme = "PaperMod"
 
[params]
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowCodeCopyButtons = true
